version: '3'
services:
  tensorflow-serving:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - ./result_model:/models/result_model
    environment:
      - MODEL_NAME=result_model