version: '3'
services:
  tensorflow-serving:
    image: tensorflow/serving
    ports:
      - "8501:8501"

    volumes:
      - ./result_model:/models/result_model
      - ./result_model/model.config.a:/models/result_model/model.config.a
    environment:
      - MODEL_NAME=result_model

    command:
      - '--model_config_file=/models/result_model/model.config.a'  